my_name = "irakli lemonjava loves programming, reading, workout"
#print(my_name[0])
#print(my_name[9])
#print(len(my_name))
#print("smoking" in my_name )
print("reading" in my_name )
cifrebi = "erti ori sami otxi xuti eqvsi shvidi"
print("erti" in cifrebi)
print(cifrebi[0])
print(len(cifrebi))
print("xuti" in cifrebi)
print(cifrebi[1])
print(len(cifrebi))
print("eqvsi" in cifrebi)
print(cifrebi[3])
print(len(cifrebi))